package Solutions;
/*
 * Author - Alexander Kohler
 * 
 */
import java.util.ArrayList;

public class Problem029 
{
/*
Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

22=4, 23=8, 24=16, 25=32
32=9, 33=27, 34=81, 35=243
42=16, 43=64, 44=256, 45=1024
52=25, 53=125, 54=625, 55=3125
If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
*/
	
	
	//Metrics - 171ms
	
	static int distinctPowers()
	{
		long startTime = System.currentTimeMillis();
		int counter = 0;
		ArrayList<Double> powerList = new ArrayList<Double>();
		
		for (int a = 2; a <= 100; a++)
		{
			for (int b = 2; b <= 100; b++)
			{
				
				//System.out.println(a + "^" + b + " : " + Math.pow(a, b));
				double pow = Math.pow(a, b);
				if (!powerList.contains(pow))
				{
				powerList.add(pow);	
				counter++;
				
				}
			}
			
		}
		System.out.println(counter);
		long endTime = System.currentTimeMillis();
		System.out.println("That took " + (endTime - startTime) + " milliseconds");
		return 0;
	}
	
	
	
	
	public static void main(String[] args) 
	{
		distinctPowers();
	}
	
}
